on:
  workflow_dispatch: {}
  schedule:
    # Makes commit(s) at 9am daily
    # Change to whatever cron expression you like
    - cron: '0 10 * * *'

jobs:
  lit-job:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    name: A job to get you lit
    steps:
      - uses: actions/checkout@v3
      - name: make commits
        # Uses GitHub action defined in https://github.com/FredaXin/gitlit
        uses: ShriBuzz/lit-init@main
        with:
          # Defines the range of number of commits
          # Change to your desierd lower and upper bound
          lower-bound: 0
          upper-bound: 6
          # Change to your GitHub username
          user-name: Shrijan Bajracharya
          # Change to your email used for GitHub account
          user-email: shrijan.buzz.5@gmail.com
